services:
  payment:
    image: mysql:8.0
    container_name: payment
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 --max-connections=600
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=payment
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
